### ISSUE TITLE
Tag the repo

### ISSUE THREAD

**Issue by beenje** [mxcube/lucid3#5]
Hello,
I could publish a conda package on conda-forge of this repo. That would make mxcube installation easier.
I only need the repo to be tagged after each new version.
Would that be possible?

It would also be nice to have the python package published on pypi.org. That would ensure no-one else takes the `lucid3` name.

**Comment by olofsvensson** [comment]
Hi Benjamin,
I have merged your pull request, I have tagged the repo with "3.0.0" and I have made a new deploy on pypi. Please check that everything looks ok for you.
I decided to set the version to 3.0.0 instead of 1.0.0 to avoid confusion concerning "lucid version 3"...

**Comment by beenje** [comment]
Thanks! lucid3 is now on conda-forge: https://github.com/conda-forge/lucid3-feedstock
